/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controladores.Alumno;
import Controladores.Materia;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class VistaInscriptos extends javax.swing.JInternalFrame {
    
    private final Set<Alumno> alumnos;

    /**
     * Creates new form VistaInscriptos
     */
    public VistaInscriptos(Set<Alumno> alumnos) {
        initComponents();
        this.alumnos = alumnos;
        cargarTabla();
    }
    
    private void cargarTabla() {
        
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"Legajo", "Apellido", "Nombre", "Materia", "Año"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        // Recorrer alumnos y sus materias
        for (Alumno a : alumnos) {
            if (a.getMaterias().isEmpty()) {
                // si no tiene materias inscriptas
                model.addRow(new Object[]{
                    a.getLegajo(),
                    a.getApellido(),
                    a.getNombre(),
                    "(sin materias)",
                    ""
                });
            } else {
                for (Materia m : a.getMaterias()) {
                    model.addRow(new Object[]{
                        a.getLegajo(),
                        a.getApellido(),
                        a.getNombre(),
                        m.getNombre(),
                        m.getAnio()
                    });
                }
            }
        }

        jt_tabla.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_lista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jp_listaLayout = new javax.swing.GroupLayout(jp_lista);
        jp_lista.setLayout(jp_listaLayout);
        jp_listaLayout.setHorizontalGroup(
            jp_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_listaLayout.setVerticalGroup(
            jp_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jt_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Legajo", "Apellido", "Nombre", "Materia", "Año"
            }
        ));
        jScrollPane1.setViewportView(jt_tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_lista;
    private javax.swing.JTable jt_tabla;
    // End of variables declaration//GEN-END:variables
}
